name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        run: pip install uv
      - name: Install the project
        run: uv sync
      - name: Ruff check
        run: uvx ruff check
      - name: Type check (ty)
        run: uvx ty check
      - name: Upload local coverage (lcov.info) if present
        if: hashFiles('lcov.info') != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: local
          fail_ci_if_error: false
      - name: Run tests
        run: uv run pytest --cov-report=lcov:github-lcov.info
      - name: Upload CI coverage (github-lcov.info) if present
        if: success() && hashFiles('github-lcov.info') != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: github-lcov.info
          flags: ci
          fail_ci_if_error: false
